export const people=[
{id:'maya',name:'Maya',age:23,place:'Fishtown',mode:'open',avatar:'avatars/aaliyah_886.svg',track:'Simulation Swarm',artist:'Big Thief',bio:'Soft distortion, hard truths, and records that make the whole apartment feel weathered.',evidence:['3 shared artists','late-night listener','12.4h together'],artists:['Big Thief','Alex G','Adrianne Lenker','Mitski','M83'],prompt:'Play me the song you keep returning to after everyone leaves.',history:['Simulation Swarm · 42m','Not · 31m'],intent:'Music-first connection'},
{id:'zuri',name:'Zuri',age:22,place:'West Philly',mode:'knock',avatar:'avatars/zuri1188.svg',track:'Aht Uh Mi Hed',artist:'Shuggie Otis',bio:'Soul records, psych detours, and the specific ache of walking home too late.',evidence:['2 mutual Tethers','soul & psych','4.8h together'],artists:['Shuggie Otis','Solange','Sly Stone','Blood Orange','Erykah Badu'],prompt:'Tell me which song changed after somebody else heard it with you.',history:['Aht Uh Mi Hed · 38m','Cranes in the Sky · 29m'],intent:'Dates'},
{id:'jordan',name:'Jordan',age:24,place:'South Philly',mode:'open',avatar:'avatars/david2582.svg',track:'That’s Us / Wild Combination',artist:'Arthur Russell',bio:'Tender music with strange edges. Usually available after midnight and before good judgment.',evidence:['Arthur Russell','active after midnight','8.1h together'],artists:['Arthur Russell','Juno','Perfume Genius','ANOHNI','Jellyfish'],prompt:'What song would make you miss a place you have never been?',history:['That’s Us · 53m','A Little Lost · 21m'],intent:'Relationship'},
{id:'noor',name:'Noor',age:21,place:'University City',mode:'open',avatar:'avatars/carol2035.svg',track:'Choker',artist:'Juno',bio:'Beautiful wreckage, maximal hooks, and jokes that become confessions halfway through.',evidence:['Juno','similar discovery habits','same broad area'],artists:['Juno','Mavi','M83','Jane Remover','The Sundays'],prompt:'Send the song that would expose you fastest.',history:['Choker · 34m'],intent:'Open to the signal'},
{id:'eli',name:'Eli',age:25,place:'Passyunk',mode:'invite',avatar:'avatars/realkevin.svg',track:'The Ghost at Number One',artist:'Jellyfish',bio:'Power-pop architecture and melodies too ornate to behave.',evidence:['Jellyfish','friends-of-friends','high discovery overlap'],artists:['Jellyfish','XTC','The Lemon Twigs','Sparks','Todd Rundgren'],prompt:'Which chorus is better constructed than most buildings?',history:[],intent:'Dates'},
{id:'hassan',name:'Hassan',age:23,place:'Cedar Park',mode:'invite',avatar:'avatars/hassan_427.svg',track:'Self Love',artist:'Mavi',bio:'Dense verses, warm samples, and long conversations that start with one bar.',evidence:['Mavi','1 mutual Tether','active evenings'],artists:['Mavi','MIKE','Navy Blue','Earl Sweatshirt','Madvillain'],prompt:'Give me one lyric worth arguing about for an hour.',history:[],intent:'Music-first connection'}
];
export const datingOrder=['zuri','jordan','noor','eli'];
export const defaultAnchors=[['Midnight City','M83','Maya','felt like the city was finally ours','JUL 08 · 47 MIN'],['That’s Us / Wild Combination','Arthur Russell','Jordan','soft enough to tell the truth','JUL 04 · 52 MIN'],['Choker','Juno','Noor','funny until it hurt','JUN 29 · 34 MIN']];
export const byId=id=>people.find(p=>p.id===id);
export const action=p=>p.mode==='open'?'Enter':p.mode==='knock'?'Knock':'Invite';
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
