"""Add physical network fields

Revision ID: 059c0a807905
Revises: 60e15022caee
Create Date: 2026-05-19 09:32:50.318183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059c0a807905'
down_revision: Union[str, Sequence[str], None] = '60e15022caee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory_anchors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_tethered_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('health', sa.Float(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sparked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('spark_token', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('spark_token')
        batch_op.drop_column('is_sparked')

    with op.batch_alter_table('memory_anchors', schema=None) as batch_op:
        batch_op.drop_column('health')
        batch_op.drop_column('last_tethered_at')

    # ### end Alembic commands ###
