"""Add Vibe Room fields

Revision ID: 5fdb82e0aaa1
Revises: 4ded8dec1947
Create Date: 2026-05-19 02:15:40.762532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fdb82e0aaa1'
down_revision: Union[str, Sequence[str], None] = '4ded8dec1947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_colors', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('backdrop_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('backdrop_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('primary_vibe', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('skia_style', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('skia_speed', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('skia_speed')
        batch_op.drop_column('skia_style')
        batch_op.drop_column('primary_vibe')
        batch_op.drop_column('backdrop_url')
        batch_op.drop_column('backdrop_type')
        batch_op.drop_column('theme_colors')

    # ### end Alembic commands ###
