"""Add unlocked_notified

Revision ID: 60e15022caee
Revises: f4d000a162c8
Create Date: 2026-05-19 02:41:50.639834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e15022caee'
down_revision: Union[str, Sequence[str], None] = 'f4d000a162c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_capsules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unlocked_notified', sa.Boolean(), nullable=True))
        batch_op.alter_column('lock_value',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_capsules', schema=None) as batch_op:
        batch_op.alter_column('lock_value',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.drop_column('unlocked_notified')

    # ### end Alembic commands ###
