"""initial_schema_with_monetization

Revision ID: d930405e01d0
Revises: 
Create Date: 2026-05-19 00:49:37.031327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd930405e01d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('initials', sa.String(length=3), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('privacy_mode', sa.String(length=16), nullable=True),
    sa.Column('ad_free_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('streaming_service', sa.String(length=16), nullable=True),
    sa.Column('has_premium', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('friendships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_a', sa.String(length=36), nullable=False),
    sa.Column('user_b', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('transparent_presence_a', sa.Boolean(), nullable=True),
    sa.Column('transparent_presence_b', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_a'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_b'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_a', 'user_b')
    )
    op.create_table('memory_anchors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('friend_id', sa.String(length=36), nullable=False),
    sa.Column('track_name', sa.String(length=256), nullable=False),
    sa.Column('artist_name', sa.String(length=256), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('pulse_count', sa.Integer(), nullable=True),
    sa.Column('mood_tag', sa.String(length=32), nullable=True),
    sa.Column('city_a', sa.String(length=128), nullable=True),
    sa.Column('city_b', sa.String(length=128), nullable=True),
    sa.Column('session_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('track_id', sa.String(length=64), nullable=True),
    sa.Column('track_name', sa.String(length=256), nullable=True),
    sa.Column('artist_name', sa.String(length=256), nullable=True),
    sa.Column('track_isrc', sa.String(length=16), nullable=True),
    sa.Column('track_duration_ms', sa.Integer(), nullable=True),
    sa.Column('track_start_epoch', sa.BigInteger(), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=True),
    sa.Column('pause_position_ms', sa.Integer(), nullable=True),
    sa.Column('next_track_name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_capsules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('track_name', sa.String(length=256), nullable=False),
    sa.Column('artist_name', sa.String(length=256), nullable=False),
    sa.Column('track_id', sa.String(length=64), nullable=True),
    sa.Column('start_position_ms', sa.Integer(), nullable=False),
    sa.Column('lock_type', sa.String(length=16), nullable=True),
    sa.Column('lock_value', sa.String(length=64), nullable=True),
    sa.Column('is_opened', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_listeners',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_listeners')
    op.drop_table('time_capsules')
    op.drop_table('sessions')
    op.drop_table('memory_anchors')
    op.drop_table('friendships')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
