"""Add CanonicalTrack and ProviderTrackMatch

Revision ID: db46ff7910d9
Revises: a1b2c3d4e5f6
Create Date: 2026-06-08 16:29:41.579593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db46ff7910d9'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_tracks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('isrc', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('artist', sa.String(length=256), nullable=False),
    sa.Column('album', sa.String(length=256), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('artwork_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canonical_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canonical_tracks_isrc'), ['isrc'], unique=True)

    op.create_table('provider_track_matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_track_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_track_id', sa.String(length=256), nullable=False),
    sa.Column('match_method', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['canonical_track_id'], ['canonical_tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_track_id')
    )
    with op.batch_alter_table('provider_track_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_track_matches_provider_track_id'), ['provider_track_id'], unique=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canonical_track_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('provider_track_id', sa.String(length=256), nullable=True))
        batch_op.create_foreign_key('fk_sessions_canonical_track', 'canonical_tracks', ['canonical_track_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sessions_canonical_track', type_='foreignkey')
        batch_op.drop_column('provider_track_id')
        batch_op.drop_column('provider')
        batch_op.drop_column('canonical_track_id')

    with op.batch_alter_table('provider_track_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_track_matches_provider_track_id'))

    op.drop_table('provider_track_matches')
    with op.batch_alter_table('canonical_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canonical_tracks_isrc'))

    op.drop_table('canonical_tracks')
    # ### end Alembic commands ###
