"""add vibe_vector

Revision ID: e63b45f89751
Revises: 059c0a807905
Create Date: 2026-05-21 12:03:56.405067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e63b45f89751'
down_revision: Union[str, Sequence[str], None] = '059c0a807905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vibe_vector', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('vibe_updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('vibe_updated_at')
        batch_op.drop_column('vibe_vector')

    # ### end Alembic commands ###
