const people=[
{u:'maya',n:'Maya',i:'MY',place:'Fishtown',mode:'open',track:'Simulation Swarm',artist:'Big Thief',e:['3 shared artists','late-night listener'],hours:'12.4h'},
{u:'zuri',n:'Zuri',i:'ZU',place:'West Philly',mode:'knock',track:'Aht Uh Mi Hed',artist:'Shuggie Otis',e:['2 mutual Tethers','soul & psych'],hours:'4.8h'},
{u:'jordan',n:'Jordan',i:'JO',place:'South Philly',mode:'open',track:'That’s Us / Wild Combination',artist:'Arthur Russell',e:['Arthur Russell','active after midnight'],hours:'8.1h'},
{u:'noor',n:'Noor',i:'NO',place:'University City',mode:'open',track:'Choker',artist:'Juno',e:['Juno','similar discovery habits'],hours:'1.6h'},
{u:'sam',n:'Sam',i:'SA',place:'Northern Liberties',mode:'invite',track:'Self Love',artist:'Mavi',e:['Mavi','1 mutual Tether'],hours:'0h'},
{u:'eli',n:'Eli',i:'EL',place:'Passyunk',mode:'invite',track:'The Ghost at Number One',artist:'Jellyfish',e:['Jellyfish','friends-of-friends'],hours:'0h'}];
const seedAnchors=[['Midnight City','M83','Maya','felt like the city was finally ours'],['That’s Us / Wild Combination','Arthur Russell','Jordan','soft enough to tell the truth'],['Choker','Juno','Noor','funny until it hurt']];
const state={view:'listen',presence:localStorage.getItem('tether:presence')||'open',filter:'close',query:'',session:null,elapsed:105,duration:243,anchors:JSON.parse(localStorage.getItem('tether:anchors')||'null')||seedAnchors,capsules:JSON.parse(localStorage.getItem('tether:capsules')||'null')||[['Maya','Open after midnight','A song for when the room gets too loud'],['Zuri','Open on your next long bus ride','No title yet']],analytics:localStorage.getItem('tether:analytics')!=='false'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function track(event,properties={}){if(!state.analytics)return;const bad=/message|search|token|latitude|longitude|phone|email|name/i;window.__tetherTelemetry=window.__tetherTelemetry||[];window.__tetherTelemetry.push({event,schemaVersion:1,properties:Object.fromEntries(Object.entries(properties).filter(([k])=>!bad.test(k)))})}
function toast(t){const n=$('#toast');n.textContent=t;n.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.remove('show'),2100)}
function action(p){return p.mode==='open'?'Join':p.mode==='knock'?'Knock':'Invite'}
function renderAvailable(){$('#available-rail').innerHTML=people.filter(p=>p.mode!=='invite').slice(0,5).map(p=>`<button class="available-card" data-person="${p.u}" data-action="${p.mode}"><span class="art">${esc(p.artist)}</span><span class="badge">${p.i}</span><strong>${p.n}</strong><small>${esc(p.track)}</small><em>${action(p)} now</em></button>`).join('')}
function renderRelationships(){$('#relationship-list').innerHTML=[['MY','You and Maya listened three nights this week.','Return to the record you left halfway through.','maya'],['JO','Jordan left the album unfinished with you.','Pick up at track seven.','jordan'],['ZU','Zuri sent something for your next late walk.','A capsule is waiting.','zuri']].map(x=>`<button class="relationship-card" data-person="${x[3]}"><b>${x[0]}</b><span><strong>${x[1]}</strong><small>${x[2]}</small></span><i>›</i></button>`).join('')}
function matches(p){const q=state.query.toLowerCase();if(q&&!`${p.n} ${p.track} ${p.artist} ${p.place} ${p.e.join(' ')}`.toLowerCase().includes(q))return false;if(state.filter==='available')return p.mode!=='invite';if(state.filter==='explore')return ['sam','noor','eli'].includes(p.u);return ['maya','zuri','jordan','noor'].includes(p.u)}
function renderPeople(){const list=people.filter(matches);$('#people-list').innerHTML=list.map(p=>`<article class="person-row"><button class="avatar" data-person="${p.u}">${p.i}</button><button class="person-copy" data-person="${p.u}"><strong>${p.n} <span>· ${p.place}</span></strong><small>${esc(p.track)} — ${esc(p.artist)}</small><em>${p.e.map(x=>`<i>${esc(x)}</i>`).join('')}</em></button><button class="row-action ${p.mode}" data-person="${p.u}" data-action="${p.mode}">${action(p)}</button></article>`).join('')||'<p class="empty">No one matched that search.</p>';track('live_presence_impression',{countBucket:String(list.length),source:state.filter})}
function renderMessages(){$('#conversation-list').innerHTML=people.slice(0,3).map((p,i)=>`<button class="conversation"><span class="avatar">${p.i}</span><span><strong>${p.n}</strong><small>${['that bass line is doing violence','left you something for the walk home','album tonight?'][i]}</small></span><time>${['now','11m','2h'][i]}</time></button>`).join('')}
function renderYou(){$('#anchor-list').innerHTML=state.anchors.slice(0,4).map(a=>`<article class="anchor"><span class="art">${esc(a[1])}</span><span><strong>${esc(a[0])} · ${esc(a[2])}</strong><small>“${esc(a[3])}”</small></span></article>`).join('');$('#capsule-list').innerHTML=state.capsules.slice(0,3).map(c=>`<article class="capsule"><i></i><span><strong>${esc(c[0])} · ${esc(c[1])}</strong><small>${esc(c[2])}</small></span></article>`).join('')}
function setPresence(mode,surface){const old=state.presence;state.presence=mode;localStorage.setItem('tether:presence',mode);const labels={open:'Open Door',knock:'Knock First',ghost:'Ghost'};$('[data-presence-menu] span').textContent=labels[mode];$$('[data-privacy]').forEach(b=>b.classList.toggle('active',b.dataset.privacy===mode));track('privacy_mode_changed',{oldMode:old,newMode:mode,surface})}
function nav(v){state.view=v;$$('.view').forEach(x=>x.classList.toggle('active',x.id===`${v}-view`));$$('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===v));scrollTo({top:0,behavior:'smooth'})}
function openPerson(u){const p=people.find(x=>x.u===u);if(!p)return;$('#person-dialog-content').innerHTML=`<div class="profile-hero"><span class="avatar">${p.i}</span><h2>${p.n}</h2><p>${p.place} · ${p.mode==='open'?'Open Door':p.mode==='knock'?'Knock First':'Not listening now'}</p></div><div class="reason"><strong>Why this may work</strong>${p.e.map(x=>`<p>✦ ${esc(x)}</p>`).join('')}<p>✦ ${p.hours} shared listening</p></div><div class="profile-actions"><button type="button" data-person="${p.u}" data-action="${p.mode}">${action(p)} listening</button><button type="button" data-message="${p.u}">Message</button></div>`;$('#person-dialog').showModal();track('match_explanation_opened',{discoverySurface:state.view})}
function startSession(p,source){if(state.presence==='ghost'&&!p){toast('Ghost keeps this private.');$('#presence-dialog').showModal();return}state.session={p,at:Date.now()};$('#stage-status').textContent=p?`Live with ${p.n}`:'Your listening is open';$('#participant-stack').innerHTML=`<span class="avatar">DT</span>${p?`<span class="avatar">${p.i}</span>`:''}`;$('#stage').classList.add('open');document.body.style.overflow='hidden';track('session_start_tapped',{surface:source,currentTrackUsed:true,privacy:state.presence});track('join_succeeded',{latencyMs:640,initialDriftBucket:'0-100ms'});clearInterval(startSession.t);startSession.t=setInterval(()=>{state.elapsed=Math.min(state.duration,state.elapsed+1);$('#stage-progress-fill').style.width=`${state.elapsed/state.duration*100}%`;$('#stage-elapsed').textContent=`${Math.floor(state.elapsed/60)}:${String(state.elapsed%60).padStart(2,'0')}`},1000)}
function endSession(){if(state.session?.p){state.anchors.unshift(['Midnight City','M83',state.session.p.n,'the exact moment was enough']);localStorage.setItem('tether:anchors',JSON.stringify(state.anchors));renderYou();track('anchor_created',{automaticOrManual:'automatic',moodAdded:false});toast(`A Memory Anchor with ${state.session.p.n} was saved.`)}state.session=null;clearInterval(startSession.t);$('#stage').classList.remove('open');document.body.style.overflow=''}
function direct(p,source){if(p.mode==='invite'){toast(`Invitation sent to ${p.n}.`);return track('invite_sent',{channel:'in_app',relationshipType:'adjacent'})}if(p.mode==='knock'){toast(`Knock sent to ${p.n}.`);track('knock_sent',{relationshipType:'friend',surface:source});return setTimeout(()=>startSession(p,'knock_accepted'),700)}startSession(p,source)}
document.addEventListener('click',e=>{const n=e.target.closest('[data-nav],[data-go]');if(n)return nav(n.dataset.nav||n.dataset.go);const a=e.target.closest('[data-action]');if(a){const p=people.find(x=>x.u===a.dataset.person);if(p)return direct(p,state.view)}const p=e.target.closest('[data-person]');if(p)return openPerson(p.dataset.person);if(e.target.closest('[data-open-listening]'))return startSession(null,'listen_hero');if(e.target.closest('[data-close-stage]'))return $('#stage').classList.remove('open');if(e.target.closest('[data-end-session]'))return endSession();if(e.target.closest('[data-presence-menu]'))return $('#presence-dialog').showModal();const sp=e.target.closest('[data-set-presence]');if(sp){setPresence(sp.dataset.setPresence,'sheet');$('#presence-dialog').close();return}const pr=e.target.closest('[data-privacy]');if(pr)return setPresence(pr.dataset.privacy,'you');if(e.target.closest('[data-open-data]'))return $('#data-dialog').showModal();if(e.target.closest('[data-open-capsule]'))return $('#capsule-dialog').showModal();const f=e.target.closest('[data-people-filter]');if(f){state.filter=f.dataset.peopleFilter;$$('[data-people-filter]').forEach(x=>x.classList.toggle('active',x===f));return renderPeople()}if(e.target.closest('[data-clear-search]')){$('#people-search').value='';state.query='';return renderPeople()}if(e.target.closest('[data-pulse]')){toast('Pulse sent.');track('pulse_sent',{sessionAgeBucket:'under_5m',pulseType:'standard'});return}if(e.target.closest('[data-send-capsule]')){state.capsules.unshift([`You → ${$('#capsule-person').value}`,$('#capsule-when').value,$('#capsule-track').value]);localStorage.setItem('tether:capsules',JSON.stringify(state.capsules));renderYou();$('#capsule-dialog').close();return toast('Capsule left for the right moment.')}if(e.target.closest('[data-queue]'))return toast('Collaborative queue opened.');if(e.target.closest('[data-invite]'))return toast('Three likely listeners are ready.');if(e.target.closest('[data-compose]'))return toast('Choose a person first—the conversation keeps its context.');if(e.target.closest('[data-message]')){$('#person-dialog').close();nav('people');return toast('Conversation opened in context.')}if(e.target.closest('[data-export-data]'))return toast('A private export would be prepared here.');if(e.target.closest('[data-delete-data]'))return toast('Local personalization history cleared.')});
$('#people-search')?.addEventListener('input',e=>{state.query=e.target.value;renderPeople()});$('[data-analytics-toggle]')?.addEventListener('change',e=>{state.analytics=e.target.checked;localStorage.setItem('tether:analytics',String(state.analytics))});
function init(){renderAvailable();renderRelationships();renderPeople();renderMessages();renderYou();setPresence(state.presence,'init');track('app_opened',{source:'direct',authState:'demo',providerConnected:true});track('now_playing_detected',{provider:'spotify',available:true,matchConfidence:'verified'})}init();
