(() => {
  "use strict";
  const KEY = "tether.install.v1";
  const STEPS = ["welcome","account","photo","profile","dating","spotify","importing","ready"];
  const MUSIC = {
    savedCount: 173,
    artists: [["Tyler, The Creator",32,"#b8c45c"],["Jeff Buckley",24,"#aaa1a8"],["My Chemical Romance",19,"#dddcd5"],["Radiohead",17,"#ef754b"],["Mac DeMarco",12,"#ebd65d"],["Billie Eilish",7,"#6e85c4"],["Frank Ocean",6,"#f18343"],["Mitski",5,"#9ea0a8"]],
    tracks: [["Like Him","Tyler, The Creator"],["Take Your Mask Off","Tyler, The Creator"],["St. Chroma","Tyler, The Creator"],["ARE WE STILL FRIENDS?","Tyler, The Creator"],["Lover, You Should’ve Come Over","Jeff Buckley"],["Last Goodbye","Jeff Buckley"],["Grace","Jeff Buckley"],["Lilac Wine","Jeff Buckley"],["Welcome to the Black Parade","My Chemical Romance"],["I’m Not Okay (I Promise)","My Chemical Romance"],["Helena","My Chemical Romance"],["Famous Last Words","My Chemical Romance"],["Weird Fishes / Arpeggi","Radiohead"],["Jigsaw Falling Into Place","Radiohead"],["Let Down","Radiohead"],["No Surprises","Radiohead"],["Moonlight on the River","Mac DeMarco"],["Still Beating","Mac DeMarco"],["One More Love Song","Mac DeMarco"],["On the Level","Mac DeMarco"],["Self Control","Frank Ocean"],["Night Shift","Lucy Dacus"],["Vampire Empire (Live)","Big Thief"],["Pink Moon","Nick Drake"],["Life On Mars?","David Bowie"],["WILDFLOWER","Billie Eilish"],["we fell in love in october","girl in red"],["Stay With Me","Miki Matsubara"],["Tokyo Reggie","Masayoshi Takanaka"],["Oh Qué Será?","Willie Colón"]],
    signals:["Album-order loyalist","Late-night listener","Emotion-first","Deep catalog explorer"]
  };
  const defaults = {step:0,complete:false,email:"",displayName:"Dylan Tague",handle:"dylantague",city:"Philadelphia",dob:"2003-10-15",pronouns:"he/him",bio:"Finding people through the songs that say it first.",identity:"Man",meet:"Women and men",intent:"Long-term relationship",structure:"Monogamous",height:"",datingEnabled:true,photo:"",spotifyConnected:false};
  let state = load(), gate;
  function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch(_){return {...defaults}}}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(_){}}
  function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
  function initials(){return state.displayName.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"ME"}
  function age(){const dob=new Date(`${state.dob}T00:00:00`);if(Number.isNaN(dob.getTime()))return 0;const now=new Date();let n=now.getFullYear()-dob.getFullYear();if(now<new Date(now.getFullYear(),dob.getMonth(),dob.getDate()))n--;return n}
  function capture(){gate?.querySelectorAll("[data-install-field]").forEach(field=>{state[field.dataset.installField]=field.type==="checkbox"?field.checked:field.value.trim()});save()}
  const copy=(k,t,p)=>`<div class="install-copy"><p class="install-kicker">${k}</p><h1>${t}</h1><p>${p}</p></div>`;
  const actions=(label,{back=true,spotify=false}={})=>`<div class="install-error" role="alert" data-install-error></div><div class="install-actions">${back?`<button class="install-back" data-install-back aria-label="Go back">←</button>`:""}<button class="install-next ${spotify?"spotify":""}" data-install-next>${label}</button></div>`;
  function welcome(){return `${copy("Welcome to Tether","Music is better when it finds someone.","Build a music identity, discover people through real taste, and listen together without giving up control.")}<div class="install-welcome-art" aria-hidden="true"><span class="install-signal"><i></i><i></i><i></i><i></i><i></i></span><span class="install-disc"></span></div><p style="color:#8f96ac;font-size:12px">This demo behaves like a fresh app install. Setup stays on this device and can be reset anytime.</p>${actions("Create my account",{back:false})}`}
  function account(){return `${copy("Your account","A home for your music life.","Sign-in is simulated here. Your password is validated, but never stored or sent anywhere.")}<form class="install-form"><label>Email<input type="email" autocomplete="email" value="${esc(state.email)}" data-install-field="email" placeholder="you@example.com"></label><label>Password<input type="password" autocomplete="new-password" minlength="8" data-password placeholder="At least 8 characters"></label><label>Username<input maxlength="24" value="${esc(state.handle)}" data-install-field="handle"></label></form>${actions("Continue securely")}`}
  function photo(){return `${copy("Make it yours","Add the face behind the taste.","Choose a photo from your device or keep a polished initials portrait. You can change it later.")}<div class="photo-stage"><div class="photo-preview">${state.photo?`<img src="${esc(state.photo)}" alt="Your selected profile photo">`:`<b>${initials()}</b>`}</div><div class="photo-choices"><button class="photo-choice primary" data-pick-photo>Choose a photo</button><button class="photo-choice" data-use-avatar>Use initials</button><input type="file" accept="image/*" data-photo-input hidden></div></div><div class="install-form" style="margin-top:22px"><label>Display name<input value="${esc(state.displayName)}" data-install-field="displayName"></label></div>${actions("Use this profile")}`}
  function profile(){return `${copy("About you","Context makes discovery kinder.","These details shape who and what you see. Sensitive details follow the visibility choices you make next.")}<form class="install-form install-form-grid"><label>Date of birth<input type="date" value="${esc(state.dob)}" data-install-field="dob"></label><label>City<input value="${esc(state.city)}" data-install-field="city"></label><label>Pronouns<input value="${esc(state.pronouns)}" data-install-field="pronouns"></label><label>Gender<select data-install-field="identity"><option>${esc(state.identity)}</option><option>Woman</option><option>Nonbinary</option><option>Self-describe</option></select></label><label class="full">Your short intro<textarea maxlength="180" data-install-field="bio">${esc(state.bio)}</textarea></label></form>${actions("Set my preferences")}`}
  function dating(){return `${copy("Dating, your way","Tell us what feels right.","Dating is optional. Messaging stays mutual and proximity stays broad—never exact.")}<div class="install-form"><label>Who would you like to meet?<select data-install-field="meet"><option>${esc(state.meet)}</option><option>Women</option><option>Men</option><option>Nonbinary people</option><option>Everyone</option></select></label><label>Relationship intent<select data-install-field="intent"><option>${esc(state.intent)}</option><option>Dating</option><option>Friendship first</option><option>Still exploring</option></select></label><label>Relationship structure<select data-install-field="structure"><option>${esc(state.structure)}</option><option>Non-monogamous</option><option>Open to discussing</option></select></label><label>Height (optional)<input value="${esc(state.height)}" data-install-field="height" placeholder="e.g. 5′ 11″"></label><div class="privacy-matrix"><div class="privacy-row"><span>Pronouns</span><select><option>Public</option><option>After match</option></select></div><div class="privacy-row"><span>Height</span><select><option>After match</option><option>Public</option><option>Do not use</option></select></div><div class="privacy-row"><span>Gender</span><select><option>Filter only</option><option>Public</option></select></div></div><label style="display:flex;grid-template-columns:auto 1fr;align-items:start"><input type="checkbox" data-install-field="datingEnabled" ${state.datingEnabled?"checked":""}><span>Turn on Dating after setup</span></label></div>${actions("Bring in my music")}`}
  function spotify(){return `${copy("Connect your music","Let your listening introduce you.","This uses the saved-track screenshots you supplied as a preloaded Spotify library. No Spotify account is contacted.")}<div class="spotify-card"><div class="spotify-lockup"><i class="spotify-logo">≈</i><span>Spotify demo authorization</span></div><p>Tether would like permission to read:</p><div class="spotify-permissions"><div><b>✓</b><span>Your music profile identity</span></div><div><b>✓</b><span>Saved tracks and top artists</span></div><div><b>✓</b><span>Listening used to explain recommendations</span></div></div></div>${actions("Connect Spotify demo",{spotify:true})}`}
  function importing(){return `${copy("Tuning your identity","Reading the music you brought.","Your supplied library is becoming the taste signals used throughout Tether.")}<div class="import-spinner"></div><div class="import-checks"><span data-check>Reading 173 saved tracks</span><span data-check>Finding your repeat artists</span><span data-check>Building Dating music identity</span><span data-check>Preparing recommendations</span></div>`}
  function ready(){return `${copy("Your Tether is ready","This sounds like you.","Your imported library now shapes the people, songs, and explanations you see—not just a badge.")}<div class="taste-result"><div class="taste-hero"><strong>${MUSIC.signals[0]}</strong><p>${MUSIC.signals.slice(1).join(" · ")}</p></div><div class="artist-stack">${MUSIC.artists.slice(0,5).map(([n,c,color],i)=>`<div class="artist-row"><i style="--artist:${color}">${i+1}</i><b>${esc(n)}</b><small>${c} saved</small></div>`).join("")}</div><div class="import-counts"><div><b>173</b><small>saved tracks</small></div><div><b>8</b><small>top artists</small></div><div><b>4</b><small>taste signals</small></div></div></div>${actions("Enter Tether",{back:false})}`}
  const views=[welcome,account,photo,profile,dating,spotify,importing,ready];
  function render(){state.step=Math.max(0,Math.min(7,state.step));save();gate.innerHTML=`<header class="install-header"><span class="install-brand"><i></i>tether</span><span class="install-step-count">${state.step+1} / 8</span></header><div class="install-progress"><i style="--progress:${(state.step+1)*12.5}%"></i></div><main class="install-body">${views[state.step]()}</main>`;wire();gate.querySelector("input,select,textarea,button")?.focus({preventScroll:true});if(STEPS[state.step]==="importing")runImport()}
  function fail(message){const el=gate.querySelector("[data-install-error]");if(el)el.textContent=message;return false}
  function valid(){capture();if(STEPS[state.step]==="account"){const pwd=gate.querySelector("[data-password]")?.value||"";if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(state.email))return fail("Enter a valid email address.");if(pwd.length<8)return fail("Use at least 8 characters.");if(!/^[a-zA-Z0-9._]{3,24}$/.test(state.handle))return fail("Username must be 3–24 letters, numbers, dots, or underscores.")}if(STEPS[state.step]==="photo"&&!state.displayName)return fail("Add the name you want people to see.");if(STEPS[state.step]==="profile"){if(age()<18){state.datingEnabled=false;save()}if(!state.city)return fail("Add your city for broad location bands.")}return true}
  function wire(){gate.querySelector("[data-install-back]")?.addEventListener("click",()=>{capture();state.step--;render()});gate.querySelector("[data-install-next]")?.addEventListener("click",()=>{if(!valid())return;if(STEPS[state.step]==="ready")return complete();state.step++;render()});const input=gate.querySelector("[data-photo-input]");gate.querySelector("[data-pick-photo]")?.addEventListener("click",()=>input?.click());gate.querySelector("[data-use-avatar]")?.addEventListener("click",()=>{state.photo="";save();render()});input?.addEventListener("change",e=>resize(e.target.files?.[0]))}
  function resize(file){if(!file?.type.startsWith("image/"))return fail("Choose an image file.");const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const canvas=document.createElement("canvas");canvas.width=240;canvas.height=300;const ctx=canvas.getContext("2d"),scale=Math.max(240/img.width,300/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(240-w)/2,(300-h)/2,w,h);state.photo=canvas.toDataURL("image/jpeg",.72);save();render()};img.src=reader.result};reader.readAsDataURL(file)}
  function runImport(){[...gate.querySelectorAll("[data-check]")].forEach((el,i)=>setTimeout(()=>el.classList.add("done"),250+i*300));setTimeout(()=>{state.spotifyConnected=true;state.step++;save();render()},1600)}
  function complete(){state.complete=true;save();gate.hidden=true;document.body.classList.remove("tether-onboarding-active");applyIdentity();globalThis.switchView?.("home")}
  function restart(){state={...defaults};save();mount(true)}
  function syncDating(){try{const key="tether.demo.dating-world.v4",d=JSON.parse(localStorage.getItem(key)||"{}");d.onboarded=true;d.discoverable=state.datingEnabled;d.profile={...(d.profile||{}),firstName:state.displayName.split(" ")[0],dob:state.dob,identity:state.identity,pronouns:state.pronouns,showMe:state.meet,intent:state.intent,structure:state.structure,bio:state.bio,anthem:"Like Him · Tyler, The Creator",proximity:"In my city"};localStorage.setItem(key,JSON.stringify(d));globalThis.TetherDatingWorld?.applyProfile?.(d.profile,state.datingEnabled)}catch(_){}}
  function applyIdentity(){if(!state.complete)return;document.querySelectorAll(".self-avatar").forEach(a=>{const f=a.querySelector(".avatar-fallback");if(f)f.textContent=initials();const img=a.querySelector("img");if(img){img.src=state.photo||"";img.hidden=!state.photo}});const title=document.querySelector("#you-title");if(title)title.textContent=state.displayName;const card=document.querySelector(".deliver-you-card");if(card){const h=card.querySelector(".handle");if(h)h.textContent=`@${state.handle} · ${state.city}`;const b=card.querySelector(".bio");if(b)b.textContent=state.bio;const chips=card.querySelector(".identity-chips");if(chips)chips.innerHTML=MUSIC.signals.slice(0,3).map(x=>`<span>${x}</span>`).join("")}const top=document.querySelector("#profile-top-five");if(top){const h=top.closest(".top-five-card")?.querySelector("h3");if(h)h.textContent=`${state.displayName.split(" ")[0]}'s Top 5`;top.innerHTML=MUSIC.artists.slice(0,5).map(([n,,color],i)=>`<button class="profile-top-five-item"><i style="background:${color}">${i+1}</i><span><b>${esc(n)}</b><small>From imported saved tracks</small></span></button>`).join("")}addCard();syncDating()}
  function addCard(){if(document.querySelector("[data-imported-card]"))return;const card=document.createElement("section");card.className="imported-music-card";card.dataset.importedCard="";card.innerHTML=`<header><div><p class="eyebrow">Your imported taste</p><h3>Picked up where Spotify left off</h3></div><button class="demo-reset-link" data-reset>Reset demo</button></header><p>173 preloaded tracks now shape recommendations, Wavelength discovery, and Dating.</p><div class="artist-chips">${MUSIC.artists.slice(0,6).map(([n])=>`<span>${esc(n)}</span>`).join("")}</div>`;document.querySelector("#home-view")?.prepend(card);card.querySelector("[data-reset]")?.addEventListener("click",restart)}
  function mount(force=false){if(!gate){gate=document.createElement("section");gate.className="install-gate";gate.setAttribute("aria-label","Tether account setup");document.querySelector(".phone")?.append(gate)}if(state.complete&&!force){gate.hidden=true;applyIdentity();return}gate.hidden=false;document.body.classList.add("tether-onboarding-active");render()}
  globalThis.TetherOnboarding={restart,getProfile:()=>({...state}),getMusicSeed:()=>structuredClone(MUSIC),completeDemo:()=>{state={...state,complete:true,spotifyConnected:true,step:7};save();mount()}};
  if(new URLSearchParams(location.search).get("fresh")==="1"){try{localStorage.removeItem(KEY)}catch(_){}state={...defaults}}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>mount(),{once:true});else mount();
})();
